name: Deploy Snap

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Publish Snap to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn workspaces focus genlayer-wallet-plugin

      - name: Build Snap
        run: yarn workspace genlayer-wallet-plugin build

      - name: Publish using Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          cd packages/snap
          npx semantic-release
